unpackaged/objects/Aam_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AAM Settings</label>
</CustomObject>

unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BW</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>CL</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CR</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>CZ</fullName>
                </value>
                <value>
                    <fullName>DK</fullName>
                </value>
                <value>
                    <fullName>EG</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>FK</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>PF</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>GH</fullName>
                </value>
                <value>
                    <fullName>GB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Address_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <formula>Address__r.Address_Line_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address Line 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Mailing Address</fullName>
                </value>
                <value>
                    <fullName>Registered Address</fullName>
                </value>
                <value>
                    <fullName>Visiting Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Local Language Address</fullName>
                </value>
                <value>
                    <fullName>Other Address</fullName>
                </value>
                <value>
                    <fullName>Other Correspondance Address</fullName>
                </value>
                <value>
                    <fullName>Reporting Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Address__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT( Address__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Address Mapping</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Mapping Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/UtilsTest.cls
@isTest
public class UtilsTest {

    public static String aAddressLine1 = 'test';
    public static String aCity = 'test';
    public static String aCountry = 'GB';
    public static String amAddressType = AddressMappingServices.ADDRESS_TYPE_VISITING_ADDRESS;
    public static Boolean amActive = true;
    public static Boolean amPrimary = false;

    public static Account account;
    public static Contact contact;

    public static Address__c address;
    public static Address__c createAddress() {
        address = new Address__c(
            Account__c = account != null ? account.Id : null,
            Address_Line_1__c = aAddressLine1,
            City__c = aCity,
            Country__c = aCountry
        );
        INSERT address;
        return address;
    }

    public static List<Address_Mapping__c> addressMappingsAccount;
    public static List<Address_Mapping__c> addressMappingsContact;

    public static List<Address_Mapping__c> createAddressMappings( Integer count ) {
        List<Address_Mapping__c> addressMappings = new List<Address_Mapping__c>();
        for( Integer i = 0; i < count; i++ ) {
            addressMappings.add(
                new Address_Mapping__c(
                    Address__c = address.Id,
                    Account__c = contact == null && account != null ? account.Id : null,
                    Contact__c = contact != null ? contact.Id : null,
                    Address_Type__c = amAddressType,
                    Active__c = amActive,
                    Primary__c = amPrimary
                )
            );
        }
        INSERT addressMappings;
        return addressMappings;
    }

    public static void createTestDataForAccount( Integer countAcc ) {
        if( countAcc > 0 ) {
            if( account == null ) {
                createAccount( true );
            }
            createAddress();
            addressMappingsAccount = createAddressMappings( countAcc );
        }
    }

    public static void createTestDataForContact( Integer countAcc, Integer countCont ) {
        createTestDataForAccount( countAcc );
        if( countCont > 0 ) {
            if( contact == null ) {
                contact = new Contact( LastName = 'test',
                                       AccountId = account.Id );
                INSERT contact;
            }
            addressMappingsContact = createAddressMappings( countCont );
        }
    }

    public static Account createAccount( Boolean doInsert ) {
        account = new Account( Name = 'test' );
        if( doInsert ) {
            INSERT account;
        }
        return account;
    }

    @isTest static void getObjectNameByIdOrPrefix() {
        String result;

        Test.startTest();
            result = Utils.getObjectNameByIdOrPrefix( '001' );
        Test.stopTest();

        System.assert( result != null );
        System.assert( result == 'Account' );
    }

    @isTest static void joinFieldValues() {
        String result;

        Test.startTest();
            result = Utils.joinFieldValues( new Address_Mapping__c( Address_Type__c = AddressMappingServices.ADDRESS_TYPE_VISITING_ADDRESS ),
                                            SObjectType.Address_Mapping__c.FieldSets.Address_List_Search_Fields.getFields() );
        Test.stopTest();

        System.assert( result != null );
    }

    @isTest static void joinFieldsInFieldSets() {
        List<Schema.FieldSetMember> result;

        Test.startTest();
            result = Utils.joinFieldsInFieldSets( SObjectType.Address_Mapping__c.FieldSets.New_Address_Additional_Information_Field.getFields(),
                                                  SObjectType.Address_Mapping__c.FieldSets.New_Address_Selected_Contacts_Fields.getFields() );
        Test.stopTest();

        System.assert( result != null );
    }

    @isTest static void getFieldsFromFieldSet() {
        List<String> result;

        Test.startTest();
            result = Utils.getFieldsFromFieldSet( SObjectType.Address_Mapping__c.FieldSets.Address_List_Search_Fields.getFields(),
                                                  Utils.addFieldsToList( null, AddressMappingWrapper.FIELDS_NEEDED_ADDRESS_WRAPPER ),
                                                  true );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void getFieldsFromFieldSet2() {
        List<String> result;

        Test.startTest();
            result = Utils.getFieldsFromFieldSet( SObjectType.Address_Mapping__c.FieldSets.Address_List_Search_Fields.getFields(),
                                                  Utils.addFieldsToList( null, AddressMappingWrapper.FIELDS_NEEDED_ADDRESS_WRAPPER ) );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void getFieldsFromObjectFields() {
        List<String> result;

        Test.startTest();
            result = Utils.getFieldsFromObjectFields( new List<Schema.SObjectField>{ Address_Mapping__c.Account__c },
                                                      new List<Schema.SObjectField>{ Address_Mapping__c.Account__c },
                                                      true );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void getFieldsFromObjectFields2() {
        List<String> result;

        Test.startTest();
            result = Utils.getFieldsFromObjectFields( new List<Schema.SObjectField>{ Address_Mapping__c.Account__c },
                                                      new List<Schema.SObjectField>{ Address_Mapping__c.Account__c } );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void getRelationshipNameCstObject() {
        String result;

        Test.startTest();
            result = Utils.getRelationshipName( 'Address__c' );
        Test.stopTest();

        System.assert( result != null );
        System.assert( result == 'Address__r.Name' );
    }

    @isTest static void getRelationshipNameStdObject() {
        String result;

        Test.startTest();
            result = Utils.getRelationshipName( 'AccountId' );
        Test.stopTest();

        System.assert( result != null );
        System.assert( result == 'Account.Name' );
    }

    @isTest static void getFieldDataForSearch() {
        List<String> results = new List<String>();

        List<Schema.FieldSetMember> members = SObjectType.Address_Mapping__c.FieldSets.New_Address_Selected_Contacts_Fields.getFields();

        Contact c = new Contact();
        Address_Mapping__c am = new Address_Mapping__c();
        am.Contact__r = c;

        Test.startTest();
        for( Schema.FieldSetMember member : members ) {
            results.add( Utils.getFieldDataForSearch( am, members[0] ) );
        }
        Test.stopTest();

        if( !members.isEmpty() ) {
            System.assert( !results.isEmpty() );
        }
    }

    @isTest static void getObjectPrefix() {
        String result;

        Test.startTest();
            result = Utils.getObjectPrefix( Address_Mapping__c.SObjectType );
        Test.stopTest();

        System.assert( result != null );
    }

    @isTest static void getFieldNames() {
        Set<String> result;

        Test.startTest();
            result = Utils.getFieldNames( new List<Schema.DescribeFieldResult>{ Address_Mapping__c.Name.getDescribe() } );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
        System.assert( result.contains( 'Name' ) );
    }

    @isTest static void getFieldNames2() {
        Set<String> result;

        FieldInfo fi = new FieldInfo( Address_Mapping__c.Name );

        Test.startTest();
            result = Utils.getFieldNames( new List<FieldInfo>{ fi } );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
        System.assert( result.contains( 'Name' ) );
    }

    @isTest static void getFieldDescribes() {
        List<Schema.DescribeFieldResult> result;

        Test.startTest();
            result = Utils.getFieldDescribes( new List<Schema.SObjectField>{ Address_Mapping__c.Name } );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void getFieldInfos() {
        List<FieldInfo> result;

        List<Schema.FieldSetMember> members = SObjectType.Address_Mapping__c.FieldSets.New_Address_Selected_Contacts_Fields.getFields();

        Test.startTest();
            result = Utils.getFieldInfos( members, null );
        Test.stopTest();

        System.assert( result != null );
        if( !members.isEmpty() ) {
            System.assert( !result.isEmpty() );
        }
    }

    @isTest static void getFieldInfos2() {
        List<FieldInfo> result;

        Test.startTest();
            result = Utils.getFieldInfos( new List<Schema.SObjectField>{ Address_Mapping__c.Name } );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void updateCustomSettingsInstall() {
        Test.startTest();
            Utils.updateCustomSettings( true );
        Test.stopTest();

        Aam_Settings__c settings = Aam_Settings__c.getOrgDefaults();
        System.assert( settings.Id != null );
    }

    @isTest static void setCustomSettings() {
        Test.startTest();
            Utils.setCustomSettings( Aam_Settings__c.getOrgDefaults() );
        Test.stopTest();
    }

    @isTest static void addField() {
        List<String> result = new List<String>();

        Test.startTest();
            Utils.addField( result, 'test' );
        Test.stopTest();

        System.assert( !result.isEmpty() );
        System.assert( result[0] == 'test' );
    }

    @isTest static void addFieldsToList() {
        List<Schema.SObjectField> result;

        Test.startTest();
            result = Utils.addFieldsToList( new List<Schema.SObjectField>{ Address_Mapping__c.Name },
                                            new List<Schema.SObjectField>{ Address_Mapping__c.Id } );
        Test.stopTest();

        System.assert( result != null );
        System.assert( !result.isEmpty() );
    }

    @isTest static void getReturnPageReference() {
        PageReference result;

        Test.startTest();
            result = Utils.getReturnPageReference( '001000000000000' );
        Test.stopTest();

        System.assert( result != null );
    }

    @isTest static void getReturnPageReferenceRetUrl() {
        PageReference result;
        Test.setCurrentPageReference( Page.AddressList );
        System.currentPageReference().getParameters().put( Utils.PARAM_RET_URL, 'test' );

        Test.startTest();
            result = Utils.getReturnPageReference( '001000000000000' );
        Test.stopTest();

        System.assert( result != null );
    }

    @isTest static void recordsAreEqualPositive() {
        Address__c address1 = new Address__c( City__c = 'test' );
        Address__c address2 = new Address__c( City__c = 'test' );

        Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>{ Address__c.City__c };

        Boolean result;

        Test.startTest();
            result = Utils.recordsAreEqual( address1, address2, fields );
        Test.stopTest();

        System.assert( result == true );
    }

    @isTest static void recordsAreEqualNegative() {
        Address__c address1 = new Address__c( City__c = 'test1' );
        Address__c address2 = new Address__c( City__c = 'test2' );

        Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>{ Address__c.City__c };

        Boolean result;

        Test.startTest();
            result = Utils.recordsAreEqual( address1, address2, fields );
        Test.stopTest();

        System.assert( result == false );
    }

    @isTest static void joinFields() {
        Set<Schema.SObjectField> fields1 = new Set<Schema.SObjectField>{ Address__c.City__c };
        Set<Schema.SObjectField> fields2 = new Set<Schema.SObjectField>{ Address__c.Address_Line_1__c };

        Set<Schema.SObjectField> result;

        Test.startTest();
            result = Utils.joinFields( fields1, fields2 );
        Test.stopTest();

        System.assert( result != null );
        for( Schema.SObjectField field : fields1 ) {
            System.assert( result.contains( field ) );
        }
        for( Schema.SObjectField field : fields2 ) {
            System.assert( result.contains( field ) );
        }
    }

    @isTest static void addFieldsToQueryNoReferenceField() {
        Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>{ Address__c.City__c, Address__c.Address_Line_1__c };
        String referenceField = null;

        String result;

        Test.startTest();
            result = Utils.addFieldsToQuery( referenceField, fields );
        Test.stopTest();

        System.assert( result != null );
        for( Schema.SObjectField field : fields ) {
            System.assert( result.contains( field.getDescribe().getName() ) );
        }
    }

    @isTest static void addFieldsToQueryWithReferenceField() {
        Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>{ Address__c.City__c, Address__c.Address_Line_1__c };
        String referenceField = 'refField';

        String result;

        Test.startTest();
            result = Utils.addFieldsToQuery( referenceField, fields );
        Test.stopTest();

        System.assert( result != null );
        for( Schema.SObjectField field : fields ) {
            System.assert( result.contains( referenceField + '.' + field.getDescribe().getName() ) );
        }
    }

    @isTest static void createStringKey() {
        Address__c address1 = new Address__c( City__c = 'test1', Address_Line_1__c = 'test2' );
        Set<Schema.SObjectField> fields = new Set<Schema.SObjectField>{ Address__c.City__c, Address__c.Address_Line_1__c };

        String result;

        Test.startTest();
            result = Utils.createStringKey( address1, fields );
        Test.stopTest();

        System.assert( result != null );
        for( Schema.SObjectField field : fields ) {
            System.assert( result.contains( (String)address1.get( field.getDescribe().getName() ) ) );
        }
    }

}