unpackaged/objects/Aam_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AAM Settings</label>
</CustomObject>

unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country_Mapping__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BW</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>CL</fullName>
                </value>
                <value>
                    <fullName>CN</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CR</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>CZ</fullName>
                </value>
                <value>
                    <fullName>DK</fullName>
                </value>
                <value>
                    <fullName>EG</fullName>
                </value>
                <value>
                    <fullName>EE</fullName>
                </value>
                <value>
                    <fullName>FK</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>PF</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>GH</fullName>
                </value>
                <value>
                    <fullName>GB</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Address_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <formula>Address__r.Address_Line_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address Line 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Mailing Address</fullName>
                </value>
                <value>
                    <fullName>Registered Address</fullName>
                </value>
                <value>
                    <fullName>Visiting Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Local Language Address</fullName>
                </value>
                <value>
                    <fullName>Other Address</fullName>
                </value>
                <value>
                    <fullName>Other Correspondance Address</fullName>
                </value>
                <value>
                    <fullName>Reporting Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Address__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Address__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT( Address__r.Country__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <formula>Address__r.Postcode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postcode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Address Mapping</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Mapping Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/MergeAddressControllerTest.cls
@isTest
private class MergeAddressControllerTest {

    public static Account account;
    public static Address__c address1;
    public static Address__c address2;
    public static List<Address__c> allAddresses { get { return new List<Address__c>{ address1, address2 }; } }
    public static Address_Mapping__c addressMapping1;
    public static Address_Mapping__c addressMapping2;
    public static MergeAddressController controller;

    public static void setup() {
        Utils.updateCustomSettings( true );
        CountryServices.recreateCountryMappings();

        account = new Account( Name = 'test' );
        INSERT account;

        address1 = new Address__c( Account__c = account.Id,
                                   Address_Line_1__c = '1 London Str. long long long long long long long long long long long long long long long long long',
                                   City__c = 'London',
                                   Postcode__c = '123',
                                   Country__c = 'GB' );
        address2 = new Address__c( Account__c = account.Id,
                                   Address_Line_1__c = '1 New York Str.',
                                   City__c = 'New York',
                                   Postcode__c = '123',
                                   Country__c = 'US' );
        INSERT new List<Address__c>{ address1, address2 };

        addressMapping1 = new Address_Mapping__c( Address__c = address1.Id,
                                                  Account__c = account.Id,
                                                  Active__c = true,
                                                  Primary__c = true,
                                                  Address_Type__c = 'Billing Address' );
        addressMapping2 = new Address_Mapping__c( Address__c = address2.Id,
                                                  Account__c = account.Id,
                                                  Active__c = true,
                                                  Primary__c = true,
                                                  Address_Type__c = 'Shipping Address' );
        INSERT new List<Address_Mapping__c>{ addressMapping1, addressMapping2 };

        controller = new MergeAddressController();
    }

    @isTest static void init() {
        setup();

        Test.startTest();
            Aam_Settings__c settings = controller.settings;
            settings = controller.getSettings();
            System.assert( settings != null );

            controller.cancel();

            List<MergeAddressController.AccountSearchResult> accountSearchResults = MergeAddressController.findAccounts( account.Name );
            System.assert( accountSearchResults != null );
            System.assert( accountSearchResults.size() == 1 );

            Id accountId = accountSearchResults[0].Id;
            System.assertEquals( account.Id, accountId );

            controller.goToStep2();
            controller.accountId = accountId;
            controller.goToStep2();

            controller.filterTextRelatedAddresses = '123';
            controller.filterRelatedAddresses();

            List<Address__c> addresses = controller.filteredRelatedAddresses;
            addresses = controller.getFilteredRelatedAddresses();
            System.assert( addresses != null );
            System.assert( addresses.size() == 2 );
            for( Address__c address : allAddresses ) {
                System.assert( new Map<Id, Address__c>( allAddresses ).containsKey( address.Id ) );
            }

            controller.goToStep3();
            controller.chosenAddresses = String.join( new List<String>{ addresses[0].Id, addresses[1].Id }, ',' );
            controller.goToStep3();

            MergeAddressController.AddressesWrapper chosenRelatedAddresses = controller.chosenRelatedAddresses;
            System.assert( chosenRelatedAddresses != null );

            Map<Id, String> recordIdToAddress = chosenRelatedAddresses.recordIdToAddress;
            recordIdToAddress = chosenRelatedAddresses.getRecordIdToAddress();
            System.assert( recordIdToAddress != null );
            System.assert( recordIdToAddress.size() == 2 );

            Map<Id, String> recordIdToAddressConcat = chosenRelatedAddresses.recordIdToAddressConcat;
            recordIdToAddressConcat = chosenRelatedAddresses.getRecordIdToAddressConcat();
            System.assert( recordIdToAddressConcat != null );
            System.assert( recordIdToAddressConcat.size() == 2 );

            System.assert( chosenRelatedAddresses.records != null );
            System.assert( chosenRelatedAddresses.records.size() == 2 );

            System.assert( chosenRelatedAddresses.fields != null );
            for( MergeAddressController.FieldWrapper field : chosenRelatedAddresses.fields ) {
                System.assert( field.selectors != null );
                System.assert( field.selectors.size() == 2 );
                System.assert( field.name != null );
                System.assert( field.editable != null );
                System.assert( field.label != null );
                System.assert( field.isCustom != null );
                System.assert( field.isDifferent != null );
                if( field.name == MergeAddressController.MASTER_RECORD_LABEL ) {
                    System.assert( field.selectors[0].selected == true );
                    System.assert( field.selectors[1].selected == false );
                }
            }

            DELETE allAddresses;
            controller.mergeAddresses();
            System.assert( ApexPages.hasMessages() );
        Test.stopTest();
    }

    @isTest static void mergeAddresses() {
        setup();

        Test.startTest();
            List<MergeAddressController.AccountSearchResult> accountSearchResults = MergeAddressController.findAccounts( account.Name );
            Id accountId = accountSearchResults[0].Id;
            controller.accountId = accountId;
            controller.goToStep2();

            List<Address__c> addresses = controller.getFilteredRelatedAddresses();
            controller.chosenAddresses = String.join( new List<String>{ addresses[0].Id, addresses[1].Id }, ',' );
            controller.goToStep3();

            Id addressIdRemaining;
            MergeAddressController.AddressesWrapper chosenRelatedAddresses = controller.chosenRelatedAddresses;
            for( MergeAddressController.FieldWrapper field : chosenRelatedAddresses.fields ) {
                if( field.name == MergeAddressController.MASTER_RECORD_LABEL ) {
                    field.selectors[0].selected = false;
                    field.selectors[1].selected = true;
                    addressIdRemaining = field.selectors[1].recordId;
                }
            }
            System.assert( addressIdRemaining != null );

            controller.mergeAddresses();
        Test.stopTest();

        List<Address__c> addressesRemaining = [ SELECT Id, Address_Line_1__c, City__c, Country__c, Postcode__c, Account__c
                                                FROM Address__c
                                                WHERE Id IN :allAddresses ];
        System.assert( !addressesRemaining.isEmpty() );
        System.assert( addressesRemaining.size() == 1 );

        Address__c addressRemaining = addressesRemaining[0];
        System.assert( addressRemaining.Id == addressIdRemaining );
        Address__c addressWithValues;
        for( Address__c address : allAddresses ) {
            if( address.Id != addressRemaining.Id ) {
                addressWithValues = address;
                break;
            }
        }
        System.assert( addressWithValues != null );
        //System.assert( addressRemaining.Address_Line_1__c == addressWithValues.Address_Line_1__c );
        //System.assert( addressRemaining.City__c == addressWithValues.City__c );
        //System.assert( addressRemaining.Country__c == addressWithValues.Country__c );
        //System.assert( addressRemaining.Postcode__c == addressWithValues.Postcode__c );
        //System.assert( addressRemaining.Account__c == account.Id );

        account = [ SELECT BillingStreet, BillingCity, BillingCountry, BillingPostalCode,
                           ShippingStreet, ShippingCity, ShippingCountry, ShippingPostalCode
                    FROM Account
                    WHERE Id = :account.Id ];

        List<Address_Mapping__c> addressMappings = [ SELECT Address__c, Address_Type__c, Primary__c, Active__c,
                                                            Address_Line_1__c, City__c, Country_Name__c, Postcode__c
                                                     FROM Address_Mapping__c
                                                     WHERE Address__c = :addressRemaining.Id ];
        System.assert( !addressMappings.isEmpty() );
        System.assert( addressMappings.size() == 2 );
        for( Address_Mapping__c addressMapping : addressMappings ) {
            System.assert( new Set<Id>{ addressMapping1.Id, addressMapping2.Id }.contains( addressMapping.Id ) );
            if( !addressMapping.Primary__c || !addressMapping.Active__c ) continue;
            if( addressMapping.Address_Type__c == 'Billing Address' ) {
                System.assert( account.BillingStreet == addressMapping.Address_Line_1__c );
                System.assert( account.BillingCity == addressMapping.City__c );
                System.assert( account.BillingCountry == addressMapping.Country_Name__c );
                System.assert( account.BillingPostalCode == addressMapping.Postcode__c );
            } else if( addressMapping.Address_Type__c == 'Shipping Address' ) {
                System.assert( account.ShippingStreet == addressMapping.Address_Line_1__c );
                System.assert( account.ShippingCity == addressMapping.City__c );
                System.assert( account.ShippingCountry == addressMapping.Country_Name__c );
                System.assert( account.ShippingPostalCode == addressMapping.Postcode__c );
            }
        }

    }

}