unpackaged/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Address_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Mailing Address</fullName>
                </value>
                <value>
                    <fullName>Registered Address</fullName>
                </value>
                <value>
                    <fullName>Visiting Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Local Language Address</fullName>
                </value>
                <value>
                    <fullName>Other Address</fullName>
                </value>
                <value>
                    <fullName>Other Correspondance Address</fullName>
                </value>
                <value>
                    <fullName>Reporting Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Removed_Date__c</fullName>
        <label>Removed Date</label>
        <type>Date</type>
    </fields>
    <label>Address Mapping</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Mapping Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/MergeServices.cls
public without sharing class MergeServices {
    
    /**
    	Merges Address Mappings related to the passed Addresses by fields: Account__c, Contact__c, Address__c, Address_Type__c, Active__c, Primary__c, CreatedDate, Removed_Date__c
    */
    public static MappingsMergeResult mergeMappings( Address__c addressToUpdate, List<Address__c>addressesToDelete ){
    	List<Address_Mapping__c> addressMappings = selectAddressMappingsForMerging(addressToUpdate, addressesToDelete);
    	checkAddressMappingsBeforeMerging(addressMappings);
        MergeServices.MappingsMergeResult mergeResult = mergeSelectedMappings( addressMappings );
        for( Address_Mapping__c mapping : mergeResult.mappingsToUpdate ) { //reparent address mappings from addresses that will be removed to address that is left
            mapping.Address__c = addressToUpdate.Id;
        }
        return mergeResult;
    }
    
    private static List<Address_Mapping__c> selectAddressMappingsForMerging(Address__c addressToUpdate, List<Address__c>addressesToDelete){
        return [ 
        		SELECT Account__c, Contact__c, Address_Type__c, Active__c, Primary__c, CreatedDate, Removed_Date__c
                FROM Address_Mapping__c
                WHERE 
                 		Address__c IN :addressesToDelete 
                 		OR Address__c = :addressToUpdate.Id
                ORDER BY 
                		Primary__c Desc,
                		CreatedDate Asc
        ];
    }
    
    private static void checkAddressMappingsBeforeMerging(List<Address_Mapping__c> addressMappings){
    	for (Address_Mapping__c mapping : addressMappings){
    		if (mapping.Account__c != null && mapping.Contact__c != null){
    			throw new AamException(Label.Address_Mapping_instance_has_both_Contact_and_Account_fields_populated + ' (' + mapping.Id + ')');
    		}
    	}
    }
    
    private static MappingsMergeResult mergeSelectedMappings( List<Address_Mapping__c> addressMappings ){
    	Map<String, Address_Mapping__c> mappingsToUpdate = new Map<String, Address_Mapping__c>();
    	List<Address_Mapping__c> mappingsToDelete = new List<Address_Mapping__c>();
    	for (Address_Mapping__c mapping : addressMappings){
    		String keyValue = getKeyFromMapping(mapping);
    		if ( mappingsToUpdate.containsKey(keyValue) ){
    			mappingsToDelete.add(mapping);
    		}else{
   				mappingsToUpdate.put(keyValue, mapping);
    		}
    	}
    	return new MappingsMergeResult(mappingsToUpdate.values(), mappingsToDelete);
    }
    
    private static String getKeyFromMapping(Address_Mapping__c mapping){
    	List<String> keyValues = new List<String>{
    			mapping.Account__c, 
    			mapping.Contact__c, 
    			mapping.Address_Type__c, 
    			String.valueOf(mapping.Active__c),
    			mapping.Active__c != true ? String.valueOf( mapping.CreatedDate.date() ) : '',
    			mapping.Active__c != true ? String.valueOf( mapping.Removed_Date__c ) : ''
    	};
    	return String.join(keyValues, '-');
    }
	
	public class MappingsMergeResult{
		
		public List<Address_Mapping__c> mappingsToUpdate { get; private set; }
		public List<Address_Mapping__c> mappingsToDelete { get; private set; }
		
		private MappingsMergeResult(List<Address_Mapping__c> mappingsToUpdate, List<Address_Mapping__c> mappingsToDelete){
			this.mappingsToUpdate = mappingsToUpdate;
			this.mappingsToDelete = mappingsToDelete;
		}
	}
	
}