unpackaged/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/BatchUpdateAddressesTest.cls
@isTest
private class BatchUpdateAddressesTest {

    @isTest static void runJob() {
        Test.startTest();
            Id batchId = Database.executebatch( new BatchUpdateAddresses(), 20 );
        Test.stopTest();

        System.assert( batchId != null );
    }

    @isTest static void runJobWithData() {
        Account account = new Account( Name = 'First Account' );
        INSERT account;

        Address__c address = new Address__c();
        address.Account__c = account.Id;
        INSERT address;

        Test.startTest();
            Id batchId = Database.executebatch( new BatchUpdateAddresses(), 20 );
        Test.stopTest();

        System.assert( batchId != null );
    }

}