unpackaged/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Country_Mapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country Mapping</label>
        <referenceTo>Country_Mapping__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <formula>Country_Mapping__r.Country_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Country_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Iso_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Country ISO Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country Mapping</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Country Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CountryServicesTest.cls
@isTest
private class CountryServicesTest {

    @isTest static void recreateCountryMappings() {

        Test.startTest();
            CountryServices.recreateCountryMappings();
        Test.stopTest();

        List<Country_Mapping__c> mappings = [ SELECT Id
                                              FROM Country_Mapping__c
                                              LIMIT 1 ];
        System.assert( !mappings.isEmpty() );
    }

    @isTest static void populateCountryMappingOnExistingAddress() {
        UtilsTest.createTestDataForAccount( 1 );
        String countryName = 'test';
        Country_Mapping__c cm;

        Test.startTest();
            cm = new Country_Mapping__c( Iso_Code__c = UtilsTest.aCountry, Country_Name__c = countryName );
            INSERT cm;
        Test.stopTest();

        List<Address__c> addresses = [ SELECT Country_Mapping__c
                                       FROM Address__c
                                       WHERE Id = :UtilsTest.address.Id ];
        System.assert( !addresses.isEmpty() );
        System.assert( addresses.size() == 1 );
        System.assert( addresses[0].Country_Mapping__c == cm.Id );
    }

    @isTest static void populateCountryMappingOnNewAddress() {
        String countryName = 'test';
        Country_Mapping__c cm = new Country_Mapping__c( Iso_Code__c = UtilsTest.aCountry, Country_Name__c = countryName );
        INSERT cm;

        Test.startTest();
            UtilsTest.createTestDataForAccount( 1 );
        Test.stopTest();

        List<Address__c> addresses = [ SELECT Country_Mapping__c
                                       FROM Address__c
                                       WHERE Id = :UtilsTest.address.Id ];
        System.assert( !addresses.isEmpty() );
        System.assert( addresses.size() == 1 );
        System.assert( addresses[0].Country_Mapping__c == cm.Id );
    }

    @isTest static void countryIsoCodeToName() {
        CountryServices.recreateCountryMappings();

        Map<String, String> countryIsoCodeToName;

        Test.startTest();
            countryIsoCodeToName = CountryServices.countryIsoCodeToName;
        Test.stopTest();

        System.assert( countryIsoCodeToName != null );
        System.assert( !countryIsoCodeToName.isEmpty() );
    }

}