unpackaged/objects/Address_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Mailing Address</fullName>
                </value>
                <value>
                    <fullName>Registered Address</fullName>
                </value>
                <value>
                    <fullName>Visiting Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>Local Language Address</fullName>
                </value>
                <value>
                    <fullName>Other Address</fullName>
                </value>
                <value>
                    <fullName>Other Correspondance Address</fullName>
                </value>
                <value>
                    <fullName>Reporting Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Mappings</relationshipLabel>
        <relationshipName>Address_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address Mapping</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Address Mapping Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Address_Mappings_Active_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Active Address Mapping Records</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ContactServices.cls
public without sharing class ContactServices {

    public static final String MAILING_ADDRESS = 'Mailing';
    public static final String OTHER_ADDRESS = 'Other';

    public static List<Contact> filterContactsWithChangedAccount( List<Contact> newContacts, Map<Id, Contact> oldContacts ) {
        List<Contact> result = new List<Contact>();
        for( Contact contact : newContacts ) {
            if( contact.AccountId == null || contact.AccountId == oldContacts.get( contact.Id ).AccountId ) continue;
            result.add( contact );
        }
        return result;
    }
    //added by chris chen 2017/07/07
    public static void emptyContactStandardMailingAddress(List<Contact> newContacts){
    	//system.debug('AddressMappingServices.isNewContactCreated is' + AddressMappingServices.isContactCreatedOrReparented);
        //if (AddressMappingServices.isNewContactCreated == true){
        	//List<Contact> consHasAccount = new List<Contact>();
        	//Set<Id> accIds = new Set<Id>();
        	Set<ID> conIds = new Set<Id>();
            for (Contact con : newContacts){
            	if (con.AccountId != null){
            		//accIds.add(con.AccountId);
            		//consHasAccount.add(con);
            		conIds.add(con.Id);
            	} 
            }
            //accIds.remove(null);
            /****
        	List<Address_Mapping__c> activeBillingAddressMappingsWithAccs = new List<Address_Mapping__c>();
        	activeBillingAddressMappingsWithAccs  = [Select Id, Contact__c,	Address_Type__c, Active__c, Account__c From Address_Mapping__c where Account__c != null and Account__c =: accIds and Active__c = true 
        	and Address_Type__c =: Utils.aamSettings.Acc_Billing_Addr_Source__c == null ? AddressMappingServices.ADDRESS_TYPE_BILLING_ADDRESS : Utils.aamSettings.Acc_Billing_Addr_Source__c];
        		
        	Map<Id, List<Address_Mapping__c>> activeBillingAddressMappingsWithAccsMap = new Map<Id, List<Address_Mapping__c>>(); 
        	for (Address_Mapping__c addMapping : activeBillingAddressMappingsWithAccs){
        		if (activeBillingAddressMappingsWithAccsMap.get(addMapping.Account__c) != null){
        			activeBillingAddressMappingsWithAccsMap.get(addMapping.Account__c).add(addMapping);
        		}
        		else{
        			activeBillingAddressMappingsWithAccsMap.put(addMapping.Account__c, new List<Address_Mapping__c>{addMapping});
        		}
        	}
        	****/        		
            //system.debug('activeBillingAddressMappingsWithAccsMap is' + activeBillingAddressMappingsWithAccsMap);
        	/****
        	List<Address_Mapping__c> activeMailingAddressMappingsWithAccs = new List<Address_Mapping__c>();
        	activeMailingAddressMappingsWithAccs  = [Select Id, Contact__c,	Address_Type__c, Active__c, Account__c From Address_Mapping__c where Account__c != null and Account__c =: accIds  
        	and Active__c = true and Address_Type__c =: Utils.aamSettings.Cont_Mailing_Addr_Source__c == null ? AddressMappingServices.ADDRESS_TYPE_MAILING_ADDRESS : Utils.aamSettings.Cont_Mailing_Addr_Source__c];
        		
        	Map<Id, List<Address_Mapping__c>> activeMailingAddressMappingsWithAccsMap = new Map<Id, List<Address_Mapping__c>>(); 
        	for (Address_Mapping__c addMapping : activeMailingAddressMappingsWithAccs){
       			if (activeMailingAddressMappingsWithAccsMap.get(addMapping.Account__c) != null){
       				activeMailingAddressMappingsWithAccsMap.get(addMapping.Account__c).add(addMapping);
       			}
       			else{
       				activeMailingAddressMappingsWithAccsMap.put(addMapping.Account__c, new List<Address_Mapping__c>{addMapping});
       			}
       		}
			****/
           	//system.debug('activeMailingAddressMappingsWithAccsMap is' + activeMailingAddressMappingsWithAccsMap);

        	List<Address_Mapping__c> activeMailingAddressMappingsWithCons = new List<Address_Mapping__c>();
        	activeMailingAddressMappingsWithCons  = [Select Id, Contact__c,	Address_Type__c, Active__c, Account__c From Address_Mapping__c where Contact__c != null and Contact__c =: conIds  
        	and Active__c = true and Address_Type__c =: Utils.aamSettings.Cont_Mailing_Addr_Source__c == null ? AddressMappingServices.ADDRESS_TYPE_MAILING_ADDRESS : Utils.aamSettings.Cont_Mailing_Addr_Source__c];
        		
        	Map<Id, List<Address_Mapping__c>> activeMailingAddressMappingsWithConsMap = new Map<Id, List<Address_Mapping__c>>(); 
        	for (Address_Mapping__c addMapping : activeMailingAddressMappingsWithCons){
       			if (activeMailingAddressMappingsWithConsMap.get(addMapping.Contact__c) != null){
       				activeMailingAddressMappingsWithConsMap.get(addMapping.Contact__c).add(addMapping);
       			}
       			else{
       				activeMailingAddressMappingsWithConsMap.put(addMapping.Contact__c, new List<Address_Mapping__c>{addMapping});
       			}
       		}

       		List<Contact> updateContactswithEmptyMailingAddress = new List<Contact>();        		
           	for (Contact con :newContacts){
           		//if (activeBillingAddressMappingsWithAccsMap.get(con.AccountId) != null && activeMailingAddressMappingsWithAccsMap.get(con.AccountId) == null){
           		//if ( activeMailingAddressMappingsWithAccsMap.get(con.AccountId) == null ){
           		if ( activeMailingAddressMappingsWithConsMap.get(con.Id) == null ){
           			system.debug('chenxu is activeMailingAddressMappingsWithConsMap' + activeMailingAddressMappingsWithConsMap.get(con.Id));
           			con.MailingStreet = null;
           			con.MailingState = null;
           			con.MailingPostalCode = null;
           			con.MailingLongitude = null;
           			con.MailingLatitude = null;
           			con.MailingCountry = null;
           			con.MailingCity = null;
           			updateContactswithEmptyMailingAddress.add(con);
           		}
           	}
           	//update updateContactswithEmptyMailingAddress;
        //}
    	
    }
	public static void zeroActiveCount (List<Contact> newContacts){
		for (Contact con : newContacts){
			con.Address_Mappings_Active_Count__c = 0;
		}
	}
    

}